/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_DpMsgComplexVC */

#ifndef _Included_at_rocworks_oa4j_jni_DpMsgComplexVC
#define _Included_at_rocworks_oa4j_jni_DpMsgComplexVC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_DpMsgComplexVC
 * Method:    getFirstGroup
 * Signature: ()Lat/rocworks/oa4j/jni/DpVCGroup;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgComplexVC_getFirstGroup
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgComplexVC
 * Method:    getNextGroup
 * Signature: ()Lat/rocworks/oa4j/jni/DpVCGroup;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgComplexVC_getNextGroup
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgComplexVC
 * Method:    getLastGroup
 * Signature: ()Lat/rocworks/oa4j/jni/DpVCGroup;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgComplexVC_getLastGroup
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgComplexVC
 * Method:    getNrOfGroups
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_DpMsgComplexVC_getNrOfGroups
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgComplexVC
 * Method:    toDebug
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_DpMsgComplexVC_toDebug
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
