/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_DpVCItem */

#ifndef _Included_at_rocworks_oa4j_jni_DpVCItem
#define _Included_at_rocworks_oa4j_jni_DpVCItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_DpVCItem
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_at_rocworks_oa4j_jni_DpVCItem_malloc
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpVCItem
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_DpVCItem_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_DpVCItem
 * Method:    toDebug
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_DpVCItem_toDebug
  (JNIEnv *, jobject, jint);

/*
 * Class:     at_rocworks_oa4j_jni_DpVCItem
 * Method:    getDpIdentifier
 * Signature: ()Lat/rocworks/oa4j/var/DpIdentifierVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpVCItem_getDpIdentifier
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpVCItem
 * Method:    setDpIdentifier
 * Signature: (Lat/rocworks/oa4j/var/DpIdentifierVar;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_DpVCItem_setDpIdentifier
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpVCItem
 * Method:    getValue
 * Signature: ()Lat/rocworks/oa4j/var/Variable;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpVCItem_getValue
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpVCItem
 * Method:    setValue
 * Signature: (Lat/rocworks/oa4j/var/Variable;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_DpVCItem_setValue
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
