/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_DpMsgManipDp */

#ifndef _Included_at_rocworks_oa4j_jni_DpMsgManipDp
#define _Included_at_rocworks_oa4j_jni_DpMsgManipDp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_DpMsgManipDp
 * Method:    isDeleteDpMsg
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_DpMsgManipDp_isDeleteDpMsg
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgManipDp
 * Method:    getDpName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_DpMsgManipDp_getDpName
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgManipDp
 * Method:    getDpId
 * Signature: ()Lat/rocworks/oa4j/var/DpIdentifierVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgManipDp_getDpId
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgManipDp
 * Method:    getDpTypeId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_DpMsgManipDp_getDpTypeId
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgManipDp
 * Method:    getDpTypeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_DpMsgManipDp_getDpTypeName
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgManipDp
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_DpMsgManipDp_toString
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgManipDp
 * Method:    toDebug
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_DpMsgManipDp_toDebug
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
