/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_DpMsgValueChange */

#ifndef _Included_at_rocworks_oa4j_jni_DpMsgValueChange
#define _Included_at_rocworks_oa4j_jni_DpMsgValueChange
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_DpMsgValueChange
 * Method:    needsAnswer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_DpMsgValueChange_needsAnswer
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgValueChange
 * Method:    setWantAnswer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_DpMsgValueChange_setWantAnswer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgValueChange
 * Method:    getFirstGroup
 * Signature: ()Lat/rocworks/oa4j/jni/DpVCGroup;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgValueChange_getFirstGroup
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgValueChange
 * Method:    getNextGroup
 * Signature: ()Lat/rocworks/oa4j/jni/DpVCGroup;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgValueChange_getNextGroup
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgValueChange
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_DpMsgValueChange_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
