/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_DpMsgHotLink */

#ifndef _Included_at_rocworks_oa4j_jni_DpMsgHotLink
#define _Included_at_rocworks_oa4j_jni_DpMsgHotLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_DpMsgHotLink
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_at_rocworks_oa4j_jni_DpMsgHotLink_malloc
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgHotLink
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_DpMsgHotLink_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
