/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_DpMsg */

#ifndef _Included_at_rocworks_oa4j_jni_DpMsg
#define _Included_at_rocworks_oa4j_jni_DpMsg
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
