/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_AnswerGroup */

#ifndef _Included_at_rocworks_oa4j_jni_AnswerGroup
#define _Included_at_rocworks_oa4j_jni_AnswerGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_AnswerGroup
 * Method:    insertItem
 * Signature: (Lat/rocworks/oa4j/var/DpIdentifierVar;Lat/rocworks/oa4j/var/Variable;Lat/rocworks/oa4j/var/TimeVar;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_AnswerGroup_insertItem
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_AnswerGroup
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_at_rocworks_oa4j_jni_AnswerGroup_malloc
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_AnswerGroup
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_AnswerGroup_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
