/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_Manager */

#ifndef _Included_at_rocworks_oa4j_jni_Manager
#define _Included_at_rocworks_oa4j_jni_Manager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetLogPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetLogPath
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetDataPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetDataPath
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetConfigValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetConfigValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiStartup
 * Signature: (I[Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiStartup
  (JNIEnv *, jobject, jint, jobjectArray, jboolean, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiShutdown
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDispatch
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDispatch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpGet
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Lat/rocworks/oa4j/var/DpIdentifierVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpGet
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpSet
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Lat/rocworks/oa4j/base/JDpVCItem;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpSet
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpSetTimed
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Lat/rocworks/oa4j/var/TimeVar;[Lat/rocworks/oa4j/base/JDpVCItem;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpSetTimed
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQuery
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQuery
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpGetPeriod
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Lat/rocworks/oa4j/var/TimeVar;Lat/rocworks/oa4j/var/TimeVar;I[Lat/rocworks/oa4j/var/DpIdentifierVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpGetPeriod
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpConnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpConnect
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpDisconnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpDisconnect
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpConnectArray
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpConnectArray
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpDisconnectArray
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpDisconnectArray
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQueryConnectSingle
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQueryConnectSingle
  (JNIEnv *, jobject, jobject, jboolean, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQueryConnectAll
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQueryConnectAll
  (JNIEnv *, jobject, jobject, jboolean, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQueryDisonnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQueryDisonnect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiAlertConnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiAlertConnect
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiAlertDisconnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiAlertDisconnect
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetIdSet
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetIdSet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetIdSetOfType
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetIdSetOfType
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpGetComment
 * Signature: (Lat/rocworks/oa4j/var/DpIdentifierVar;)Lat/rocworks/oa4j/var/LangTextVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpGetComment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiSendArchivedDPs
 * Signature: (Lat/rocworks/oa4j/var/DynVar;Z)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiSendArchivedDPs
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiSetManagerState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Manager_apiSetManagerState
  (JNIEnv *, jobject, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiProcessHotlinkGroup
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiProcessHotlinkGroup
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetConnectionState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetConnectionState
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiIsActiveConnection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiIsActiveConnection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
