/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_Msg */

#ifndef _Included_at_rocworks_oa4j_jni_Msg
#define _Included_at_rocworks_oa4j_jni_Msg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    isA
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Msg_isA
  (JNIEnv *, jobject, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    getMsgId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_at_rocworks_oa4j_jni_Msg_getMsgId
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    forwardMsg
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Msg_forwardMsg
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    forwardMsgToData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Msg_forwardMsgToData
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    getSourceManTypeNr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Msg_getSourceManTypeNr
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    getSourceManNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Msg_getSourceManNum
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Msg_toString
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    toDebug
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Msg_toDebug
  (JNIEnv *, jobject, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Msg
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Msg_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
