/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_DpMsgRequest */

#ifndef _Included_at_rocworks_oa4j_jni_DpMsgRequest
#define _Included_at_rocworks_oa4j_jni_DpMsgRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_DpMsgRequest
 * Method:    getFirstGroup
 * Signature: ()Lat/rocworks/oa4j/jni/RequestGroup;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgRequest_getFirstGroup
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgRequest
 * Method:    getNextGroup
 * Signature: ()Lat/rocworks/oa4j/jni/RequestGroup;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_DpMsgRequest_getNextGroup
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgRequest
 * Method:    getMultipleAnswersAllowed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_DpMsgRequest_getMultipleAnswersAllowed
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_DpMsgRequest
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_DpMsgRequest_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
