/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_SysMsg */

#ifndef _Included_at_rocworks_oa4j_jni_SysMsg
#define _Included_at_rocworks_oa4j_jni_SysMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_SysMsg
 * Method:    getSysMsgType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_SysMsg_getSysMsgType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_SysMsg
 * Method:    getSysMsgSubType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_SysMsg_getSysMsgSubType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_SysMsg
 * Method:    getInitSysMsgData
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_SysMsg_getInitSysMsgData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
