/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_rocworks_oa4j_jni_Manager */

#ifndef _Included_at_rocworks_oa4j_jni_Manager
#define _Included_at_rocworks_oa4j_jni_Manager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetLogPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetLogPath
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetDataPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetDataPath
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetConfigValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetConfigValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetSystemNum
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetSystemNum
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiStartup
 * Signature: (I[Ljava/lang/String;ZZZZ)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiStartup
  (JNIEnv *, jobject, jint, jobjectArray, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiShutdown
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDispatch
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDispatch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpGet
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Lat/rocworks/oa4j/var/DpIdentifierVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpGet
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpSet
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Lat/rocworks/oa4j/base/JDpVCItem;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpSet
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpSetTimed
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Lat/rocworks/oa4j/var/TimeVar;[Lat/rocworks/oa4j/base/JDpVCItem;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpSetTimed
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQuery
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQuery
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpGetPeriod
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Lat/rocworks/oa4j/var/TimeVar;Lat/rocworks/oa4j/var/TimeVar;I[Lat/rocworks/oa4j/var/DpIdentifierVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpGetPeriod
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpConnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpConnect
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpDisconnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpDisconnect
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpConnectArray
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpConnectArray
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpDisconnectArray
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpDisconnectArray
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQueryConnectSingle
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQueryConnectSingle
  (JNIEnv *, jobject, jobject, jboolean, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQueryConnectAll
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQueryConnectAll
  (JNIEnv *, jobject, jobject, jboolean, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpQueryDisconnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpQueryDisconnect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiAlertConnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiAlertConnect
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiAlertDisconnect
 * Signature: (Lat/rocworks/oa4j/base/JHotLinkWaitForAnswer;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiAlertDisconnect
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetIdSet
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetIdSet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetIdSetOfType
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetIdSetOfType
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpGetComment
 * Signature: (Lat/rocworks/oa4j/var/DpIdentifierVar;)Lat/rocworks/oa4j/var/LangTextVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpGetComment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    checkPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_checkPassword
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    setUserId
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_Manager_setUserId
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDoReceiveSysMsg
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDoReceiveSysMsg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDoReceiveDpMsg
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDoReceiveDpMsg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiSendArchivedDPs
 * Signature: (Lat/rocworks/oa4j/var/DynVar;Z)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiSendArchivedDPs
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiSetManagerState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Manager_apiSetManagerState
  (JNIEnv *, jobject, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiProcessHotlinkGroup
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiProcessHotlinkGroup
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiGetConnectionState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiGetConnectionState
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiIsActiveConnection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiIsActiveConnection
  (JNIEnv *, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiLog
 * Signature: (IJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_rocworks_oa4j_jni_Manager_apiLog
  (JNIEnv *, jobject, jint, jlong, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpTypeGet
 * Signature: (Ljava/lang/String;Z)Lat/rocworks/oa4j/var/DpTypeElement;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpTypeGet
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpTypeGetFlat
 * Signature: (Ljava/lang/String;Z)Lat/rocworks/oa4j/var/DpTypeResult;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpTypeGetFlat
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsCreateView
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lat/rocworks/oa4j/var/LangTextVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsCreateView
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsDeleteView
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsDeleteView
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetViews
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetViews
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetViewDisplayNames
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lat/rocworks/oa4j/var/LangTextVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetViewDisplayNames
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsChangeViewDisplayNames
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lat/rocworks/oa4j/var/LangTextVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsChangeViewDisplayNames
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetViewSeparators
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetViewSeparators
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsChangeViewSeparators
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsChangeViewSeparators
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsAddTree
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILat/rocworks/oa4j/var/DpIdentifierVar;Lat/rocworks/oa4j/var/LangTextVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsAddTree
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsDeleteTree
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsDeleteTree
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetTrees
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetTrees
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetRoot
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetRoot
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsAddNode
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILat/rocworks/oa4j/var/DpIdentifierVar;Lat/rocworks/oa4j/var/LangTextVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsAddNode
  (JNIEnv *, jobject, jstring, jstring, jint, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetChildren
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetChildren
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetParent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetParent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsChangeNodeData
 * Signature: (Ljava/lang/String;Lat/rocworks/oa4j/var/DpIdentifierVar;I)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsChangeNodeData
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsChangeNodeDisplayNames
 * Signature: (Ljava/lang/String;Lat/rocworks/oa4j/var/LangTextVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsChangeNodeDisplayNames
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetNode
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetId
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetNodesByName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetNodesByName
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetNodesByData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lat/rocworks/oa4j/var/DpIdentifierVar;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetNodesByData
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsSubStr
 * Signature: (Ljava/lang/String;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsSubStr
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetSystemNames
 * Signature: (Ljava/lang/String;)Lat/rocworks/oa4j/var/LangTextVar;
 */
JNIEXPORT jobject JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetSystemNames
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsSetSystemNames
 * Signature: (Ljava/lang/String;Lat/rocworks/oa4j/var/LangTextVar;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsSetSystemNames
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsCheckId
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsCheckId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsCheckName
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsCheckName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsCheckSeparator
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsCheckSeparator
  (JNIEnv *, jobject, jchar);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsGetIdSet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)[Lat/rocworks/oa4j/var/DpIdentifierVar;
 */
JNIEXPORT jobjectArray JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsGetIdSet
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsAddObserver
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsAddObserver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiCnsRemoveObserver
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiCnsRemoveObserver
  (JNIEnv *, jobject, jint);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpTypeCreate
 * Signature: (Lat/rocworks/oa4j/var/DpTypeElement;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpTypeCreate
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpTypeChange
 * Signature: (ILat/rocworks/oa4j/var/DpTypeElement;ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpTypeChange
  (JNIEnv *, jobject, jint, jobject, jboolean, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpTypeDelete
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpTypeDelete
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpTypeNameToId
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpTypeNameToId
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpCreate
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpDelete
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpDelete
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_rocworks_oa4j_jni_Manager
 * Method:    apiDpExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_rocworks_oa4j_jni_Manager_apiDpExists
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
